In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [63]:
df = pd.read_csv("Placement_Data_Full_Class.csv")
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [64]:
df.isna().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [65]:
df['salary'] = df['salary'].fillna(df['salary'].mean())
df.isna().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [66]:
df = df.drop(['sl_no', 'salary'], axis = 1)
df

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed

In [67]:
df['status'].nunique()

2

In [68]:
df['status'] = df['status'].replace({'Placed': 1, 'Not Placed': 0})
df

<ipython-input-68-df9d8a8d4867>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['status'] = df['status'].replace({'Placed': 1, 'Not Placed': 0})

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,1
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,1
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,1
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,0
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,1
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,1
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,1
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,1
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,0

In [69]:
df['ssc_b'].nunique()

2

In [70]:
df['ssc_b'] = df['ssc_b'].replace({'Central': 1, 'Others': 0})
df

<ipython-input-70-266d19bc31df>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['ssc_b'] = df['ssc_b'].replace({'Central': 1, 'Others': 0})

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,1
1,M,79.33,1,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,1
2,M,65.00,1,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,1
3,M,56.00,1,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,0
4,M,85.80,1,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,0,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,1
211,M,58.00,0,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,1
212,M,67.00,0,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,1
213,F,74.00,0,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,1
214,M,62.00,1,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,0

In [71]:
df['workex'].nunique()

2

In [72]:
df['workex'] = df['workex'].replace({'Yes': 1, 'No': 0})
df

<ipython-input-72-b4e036a58908>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['workex'] = df['workex'].replace({'Yes': 1, 'No': 0})

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,Others,Commerce,58.00,Sci&Tech,0,55.0,Mkt&HR,58.80,1
1,M,79.33,1,78.33,Others,Science,77.48,Sci&Tech,1,86.5,Mkt&Fin,66.28,1
2,M,65.00,1,68.00,Central,Arts,64.00,Comm&Mgmt,0,75.0,Mkt&Fin,57.80,1
3,M,56.00,1,52.00,Central,Science,52.00,Sci&Tech,0,66.0,Mkt&HR,59.43,0
4,M,85.80,1,73.60,Central,Commerce,73.30,Comm&Mgmt,0,96.8,Mkt&Fin,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,0,82.00,Others,Commerce,77.60,Comm&Mgmt,0,91.0,Mkt&Fin,74.49,1
211,M,58.00,0,60.00,Others,Science,72.00,Sci&Tech,0,74.0,Mkt&Fin,53.62,1
212,M,67.00,0,67.00,Others,Commerce,73.00,Comm&Mgmt,1,59.0,Mkt&Fin,69.72,1
213,F,74.00,0,66.00,Others,Commerce,58.00,Comm&Mgmt,0,70.0,Mkt&HR,60.23,1
214,M,62.00,1,58.00,Others,Science,53.00,Comm&Mgmt,0,89.0,Mkt&HR,60.22,0

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gender          215 non-null    object
 1   ssc_p           215 non-null    float64
 2   ssc_b           215 non-null    int64
 3   hsc_p           215 non-null    float64
 4   hsc_b           215 non-null    object
 5   hsc_s           215 non-null    object
 6   degree_p        215 non-null    float64
 7   degree_t        215 non-null    object
 8   workex          215 non-null    int64
 9   etest_p         215 non-null    float64
 10  specialisation  215 non-null    object
 11  mba_p           215 non-null    float64
 12  status          215 non-null    int64
dtypes: float64(5), int64(3), object(5)
memory usage: 22.0+ KB

In [74]:
df['gender'] = df['gender'].replace({'M': 1, 'F': 0})
df

<ipython-input-74-267fb1ff9759>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender'] = df['gender'].replace({'M': 1, 'F': 0})

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,1,67.00,0,91.00,Others,Commerce,58.00,Sci&Tech,0,55.0,Mkt&HR,58.80,1
1,1,79.33,1,78.33,Others,Science,77.48,Sci&Tech,1,86.5,Mkt&Fin,66.28,1
2,1,65.00,1,68.00,Central,Arts,64.00,Comm&Mgmt,0,75.0,Mkt&Fin,57.80,1
3,1,56.00,1,52.00,Central,Science,52.00,Sci&Tech,0,66.0,Mkt&HR,59.43,0
4,1,85.80,1,73.60,Central,Commerce,73.30,Comm&Mgmt,0,96.8,Mkt&Fin,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,1,80.60,0,82.00,Others,Commerce,77.60,Comm&Mgmt,0,91.0,Mkt&Fin,74.49,1
211,1,58.00,0,60.00,Others,Science,72.00,Sci&Tech,0,74.0,Mkt&Fin,53.62,1
212,1,67.00,0,67.00,Others,Commerce,73.00,Comm&Mgmt,1,59.0,Mkt&Fin,69.72,1
213,0,74.00,0,66.00,Others,Commerce,58.00,Comm&Mgmt,0,70.0,Mkt&HR,60.23,1
214,1,62.00,1,58.00,Others,Science,53.00,Comm&Mgmt,0,89.0,Mkt&HR,60.22,0

In [75]:
df['specialisation'].nunique()

2

In [77]:
df['specialisation'] = df['specialisation'].replace({'Mkt&HR': 1, 'Mkt&Fin': 0})
df

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,1,67.00,0,91.00,Others,Commerce,58.00,Sci&Tech,0,55.0,1,58.80,1
1,1,79.33,1,78.33,Others,Science,77.48,Sci&Tech,1,86.5,0,66.28,1
2,1,65.00,1,68.00,Central,Arts,64.00,Comm&Mgmt,0,75.0,0,57.80,1
3,1,56.00,1,52.00,Central,Science,52.00,Sci&Tech,0,66.0,1,59.43,0
4,1,85.80,1,73.60,Central,Commerce,73.30,Comm&Mgmt,0,96.8,0,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,1,80.60,0,82.00,Others,Commerce,77.60,Comm&Mgmt,0,91.0,0,74.49,1
211,1,58.00,0,60.00,Others,Science,72.00,Sci&Tech,0,74.0,0,53.62,1
212,1,67.00,0,67.00,Others,Commerce,73.00,Comm&Mgmt,1,59.0,0,69.72,1
213,0,74.00,0,66.00,Others,Commerce,58.00,Comm&Mgmt,0,70.0,1,60.23,1
214,1,62.00,1,58.00,Others,Science,53.00,Comm&Mgmt,0,89.0,1,60.22,0

In [78]:
df['hsc_b'].nunique()

2

In [79]:
df['hsc_b'] = df['hsc_b'].replace({'Central': 1, 'Others': 0})
df

<ipython-input-79-69e9f22b618b>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['hsc_b'] = df['hsc_b'].replace({'Central': 1, 'Others': 0})

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,1,67.00,0,91.00,0,Commerce,58.00,Sci&Tech,0,55.0,1,58.80,1
1,1,79.33,1,78.33,0,Science,77.48,Sci&Tech,1,86.5,0,66.28,1
2,1,65.00,1,68.00,1,Arts,64.00,Comm&Mgmt,0,75.0,0,57.80,1
3,1,56.00,1,52.00,1,Science,52.00,Sci&Tech,0,66.0,1,59.43,0
4,1,85.80,1,73.60,1,Commerce,73.30,Comm&Mgmt,0,96.8,0,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,1,80.60,0,82.00,0,Commerce,77.60,Comm&Mgmt,0,91.0,0,74.49,1
211,1,58.00,0,60.00,0,Science,72.00,Sci&Tech,0,74.0,0,53.62,1
212,1,67.00,0,67.00,0,Commerce,73.00,Comm&Mgmt,1,59.0,0,69.72,1
213,0,74.00,0,66.00,0,Commerce,58.00,Comm&Mgmt,0,70.0,1,60.23,1
214,1,62.00,1,58.00,0,Science,53.00,Comm&Mgmt,0,89.0,1,60.22,0

In [80]:
df['hsc_s'].nunique()

3

In [81]:
df['hsc_s'] = df['hsc_s'].replace({'Commerce': 1, 'Science': 0, 'Arts': 2})
df

<ipython-input-81-9daf8ee4c71c>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['hsc_s'] = df['hsc_s'].replace({'Commerce': 1, 'Science': 0, 'Arts': 2})

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,1,67.00,0,91.00,0,1,58.00,Sci&Tech,0,55.0,1,58.80,1
1,1,79.33,1,78.33,0,0,77.48,Sci&Tech,1,86.5,0,66.28,1
2,1,65.00,1,68.00,1,2,64.00,Comm&Mgmt,0,75.0,0,57.80,1
3,1,56.00,1,52.00,1,0,52.00,Sci&Tech,0,66.0,1,59.43,0
4,1,85.80,1,73.60,1,1,73.30,Comm&Mgmt,0,96.8,0,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,1,80.60,0,82.00,0,1,77.60,Comm&Mgmt,0,91.0,0,74.49,1
211,1,58.00,0,60.00,0,0,72.00,Sci&Tech,0,74.0,0,53.62,1
212,1,67.00,0,67.00,0,1,73.00,Comm&Mgmt,1,59.0,0,69.72,1
213,0,74.00,0,66.00,0,1,58.00,Comm&Mgmt,0,70.0,1,60.23,1
214,1,62.00,1,58.00,0,0,53.00,Comm&Mgmt,0,89.0,1,60.22,0

In [82]:
df['degree_t'].nunique()

3

In [83]:
df1 = df['degree_t'].str.get_dummies(sep='&')
df1

     Comm  Mgmt  Others  Sci  Tech
0       0     0       0    1     1
1       0     0       0    1     1
2       1     1       0    0     0
3       0     0       0    1     1
4       1     1       0    0     0
..    ...   ...     ...  ...   ...
210     1     1       0    0     0
211     0     0       0    1     1
212     1     1       0    0     0
213     1     1       0    0     0
214     1     1       0    0     0

[215 rows x 5 columns]

In [84]:
df = pd.concat([df, df1], axis=1)
df.drop("degree_t", axis=1, inplace=True)
df

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,workex,etest_p,specialisation,mba_p,status,Comm,Mgmt,Others,Sci,Tech
0,1,67.00,0,91.00,0,1,58.00,0,55.0,1,58.80,1,0,0,0,1,1
1,1,79.33,1,78.33,0,0,77.48,1,86.5,0,66.28,1,0,0,0,1,1
2,1,65.00,1,68.00,1,2,64.00,0,75.0,0,57.80,1,1,1,0,0,0
3,1,56.00,1,52.00,1,0,52.00,0,66.0,1,59.43,0,0,0,0,1,1
4,1,85.80,1,73.60,1,1,73.30,0,96.8,0,55.50,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,1,80.60,0,82.00,0,1,77.60,0,91.0,0,74.49,1,1,1,0,0,0
211,1,58.00,0,60.00,0,0,72.00,0,74.0,0,53.62,1,0,0,0,1,1
212,1,67.00,0,67.00,0,1,73.00,1,59.0,0,69.72,1,1,1,0,0,0
213,0,74.00,0,66.00,0,1,58.00,0,70.0,1,60.23,1,1,1,0,0,0
214,1,62.00,1,58.00,0,0,53.00,0,89.0,1,60.22,0,1,1,0,0,0

In [85]:
X = df.drop(['status'], axis=1)
y = df['status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
model = LogisticRegression()
model.fit(X_train, y_train)
answers_pred = model.predict(X_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [86]:
model.coef_

array([[ 0.31661313,  0.16047555, -0.96277853,  0.108265  ,  0.18737421,
        -0.4123851 ,  0.07404541,  1.75318955, -0.02438046, -0.65371372,
        -0.233477  , -0.31153802, -0.31153802, -0.62114926, -0.61102671,
        -0.61102671]])

In [87]:
tn, fp, fn, tp = confusion_matrix(y_test, answers_pred).ravel()
print("TP:", tp)
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)

TP: 40
TN: 14
FP: 7
FN: 4

In [88]:
accuracy_score(y_test, answers_pred)

0.8307692307692308

In [89]:
recall_score(y_test, answers_pred)

0.9090909090909091

In [90]:
precision_score(y_test, answers_pred)

0.851063829787234

In [93]:
f1_score(y_test, answers_pred)

0.8791208791208791